export const USERNAME_CHANGED = "USERNAME_CHANGED";
export const USEREMAIL_CHANGED = "USEREMAIL_CHANGED";
export const USERPASSWORD_CHANGED = "USERPASSWORD_CHANGED";
export const USERCONFIRMPASSWORD_CHANGED = "USERCONFIRMPASSWORD_CHANGED";
export const USERTOKEN_CHANGED = "USERTOKEN_CHANGED";